version: '3.4'
services:
  eth2keygen.avado.dnp.dappnode.eth:
    image: 'eth2keygen.avado.dnp.dappnode.eth:0.0.15'
    build: ./build
    environment:
      - EXTRA_OPTS=
    volumes:
      - 'data:/data'
    ports:
      - '80:80'
      - '82:82'
volumes:
  data: {}
